#!/bin/bash

cleanup() {
  echo "Cleanup backup older than $CLEANUP_OLDER_THAN days"
  toberemove=$(find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
  echo "Will try to remove $toberemove files"
  find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
}

if [ -z "$MYSQL_ENV_MYSQL_HOST" ]; then echo "Error: MYSQL_ENV_MYSQL_HOST not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$WORDPRESS_ENV_WORDPRESS_DB_USER" ]; then echo "Error: WORDPRESS_ENV_WORDPRESS_DB_USER not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$WORDPRESS_ENV_WORDPRESS_DB_NAME" ]; then echo "Error: WORDPRESS_ENV_WORDPRESS_DB_NAME not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$WORDPRESS_ENV_WORDPRESS_DB_PASSWORD" ]; then echo "Error: WORDPRESS_ENV_WORDPRESS_DB_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi

if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi

echo 'creating backup archive of /var/www/html'
tar --create --gzip -vv --directory="/var/www/html/" --file="/backups/backup_`date '+%Y%m%d%H%M%S'`.tar.gz" "./"

echo 'creating database dump'
mysqldump -h $MYSQL_ENV_MYSQL_HOST --add-drop-table -u$WORDPRESS_ENV_WORDPRESS_DB_USER -p $WORDPRESS_ENV_WORDPRESS_DB_NAME --password=$WORDPRESS_ENV_WORDPRESS_DB_PASSWORD | bzip2 -c > /backups/backup_`date '+%Y%m%d%H%M%S'`.sql.bz2

echo 'Finished: SUCCESS'
